**Creating Numpy Array**

In [3]:
import numpy as np

In [4]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [6]:
prices = [10,20,30,40]
prices_array = np.array(prices)
prices_array

array([10, 20, 30, 40])

In [7]:
names = ['John','Matt','Rob']
names_array = np.array(names)
names_array

array(['John', 'Matt', 'Rob'], dtype='<U4')

In [8]:
names_array[0]

'John'

In [9]:
mullti_array = np.array([[1,2,3],[4,5,6]])
mullti_array

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
mullti_array[0]

array([1, 2, 3])

In [11]:
mullti_array[0][1]

2

In [12]:
mullti_array[1][2]

6

In [13]:
mullti_array.ndim

2

In [14]:
names_array.ndim

1

In [15]:
mullti_array.dtype

dtype('int32')

In [16]:
names_array.dtype

dtype('<U4')

**Array Type Convention**