**Creating Numpy Array**

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [3]:
prices = [10,20,30,40]
prices_array = np.array(prices)
prices_array

array([10, 20, 30, 40])

In [4]:
names = ['John','Matt','Rob']
names_array = np.array(names)
names_array

array(['John', 'Matt', 'Rob'], dtype='<U4')

In [5]:
names_array[0]

'John'

In [6]:
mullti_array = np.array([[1,2,3],[4,5,6]])
mullti_array

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
mullti_array[0]

array([1, 2, 3])

In [8]:
mullti_array[0][1]

2

In [9]:
mullti_array[1][2]

6

In [10]:
mullti_array.ndim

2

In [11]:
names_array.ndim

1

In [12]:
mullti_array.dtype

dtype('int32')

In [13]:
names_array.dtype

dtype('<U4')

**Array Type Convention**

In [16]:
auto_array = np.zeros(10)
auto_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
auto_array.dtype

dtype('float64')

In [18]:
auto_array=auto_array.astype(np.int64)
auto_array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [19]:
array = np.array([1,2,3,4],dtype=np.float64)
array

array([1., 2., 3., 4.])

In [20]:
array.dtype

dtype('int32')

In [23]:
array = array.astype(np.int64)

In [24]:
array

array([1, 2, 3, 4], dtype=int64)

**Arithmetic Operations**

In [26]:
list_a = [[1,2,3],[4,5,6]]
list_b = [[7,8,9],[10,11,12]]
array_a = np.array(list_a)
array_b = np.array(list_b)

In [27]:
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
array_b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [29]:
array_a + array_b

array([[ 8, 10, 12],
       [14, 16, 18]])

In [30]:
array_a * array_b

array([[ 7, 16, 27],
       [40, 55, 72]])

In [31]:
array_a * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [32]:
array_b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [33]:
array_b / 10

array([[0.7, 0.8, 0.9],
       [1. , 1.1, 1.2]])

**Comparing Arrays**

In [34]:
array_b ** 2

array([[ 49,  64,  81],
       [100, 121, 144]])

In [35]:
array_a > array_b

array([[False, False, False],
       [False, False, False]])

In [36]:
array_a < array_b

array([[ True,  True,  True],
       [ True,  True,  True]])

In [37]:
res = array_a < array_b
res

array([[ True,  True,  True],
       [ True,  True,  True]])

In [38]:
res.dtype

dtype('bool')

**Indexing and Slicing Arrays**

In [39]:
arr = np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [40]:
arr[0]

10

In [41]:
arr[3]

40

In [44]:
arr = np.array([[1,2,3],[4,5,6]])

In [46]:
arr[1][2]

6

In [47]:
#Slicing
arr = np.array([10,20,30,40,50,60,70])
arr

array([10, 20, 30, 40, 50, 60, 70])

In [48]:
arr[1:5]

array([20, 30, 40, 50])

In [55]:
multi_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
multi_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
multi_array[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [57]:
multi_array[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [58]:
multi_array[0:2,0:2]

array([[1, 2],
       [4, 5]])

**Fancy and Boolean Indexing**

In [59]:
multi_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
#Fancy indexing
multi_array[[0,0,2,2],[0,2,0,2]]

array([1, 3, 7, 9])

In [61]:
#Boolean indexing
mullti_array[multi_array>5]

array([6, 7, 8, 9])